// === FILE: src/maps.js ===
// Map definitions – 14×10 grid, path as [col,row] waypoints

export const MAPS = [
  {
    id:         'forest',
    name:       'Forest Path',
    icon:       '🌲',
    difficulty: 1,
    unlockWave: 0,
    bgColor:    '#0d1f0d',
    pathColor:  '#5a3e1b',
    grassColor: '#1a3a1a',
    waypoints: [
      { col: -1, row: 2 },  // entry (off-screen left)
      { col:  3, row: 2 },
      { col:  3, row: 6 },
      { col:  7, row: 6 },
      { col:  7, row: 1 },
      { col: 11, row: 1 },
      { col: 11, row: 8 },
      { col: 14, row: 8 },  // exit (off-screen right)
    ],
    lives:     20,
    startGold: 200,
    waves:     40,
  },
  {
    id:         'desert',
    name:       'Desert Dunes',
    icon:       '🏜️',
    difficulty: 2,
    unlockWave: 10,
    bgColor:    '#1f1a0d',
    pathColor:  '#8B6914',
    grassColor: '#2a2010',
    waypoints: [
      { col: -1, row: 1 },
      { col:  5, row: 1 },
      { col:  5, row: 5 },
      { col:  2, row: 5 },
      { col:  2, row: 8 },
      { col:  9, row: 8 },
      { col:  9, row: 3 },
      { col: 13, row: 3 },
      { col: 13, row: 7 },
      { col: 14, row: 7 },
    ],
    lives:     15,
    startGold: 180,
    waves:     50,
  },
  {
    id:         'volcano',
    name:       'Volcanic Rift',
    icon:       '🌋',
    difficulty: 3,
    unlockWave: 25,
    bgColor:    '#1f0d0d',
    pathColor:  '#6b1a1a',
    grassColor: '#2a1010',
    waypoints: [
      { col: -1, row: 5 },
      { col:  2, row: 5 },
      { col:  2, row: 1 },
      { col:  6, row: 1 },
      { col:  6, row: 8 },
      { col: 10, row: 8 },
      { col: 10, row: 3 },
      { col: 13, row: 3 },
      { col: 13, row: 7 },
      { col: 14, row: 7 },
    ],
    lives:     10,
    startGold: 150,
    waves:     60,
  },
];
